### ISSUE TITLE
The download of dataset hm3d_train_v0.2 was unsuccessful

### ISSUE THREAD

**Issue by orange0131** [bdaiinstitute/vlfm#37]
In Clone and install habitat-lab, then download datasets
In this step, the run is finished
python -m habitat_sim.utils.datasets_download 
  --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET 
  --uids hm3d_train_v0.2 
  --data-path $DATA_DIR &&
python -m habitat_sim.utils.datasets_download 
  --username $MATTERPORT_TOKEN_ID --password $MATTERPORT_TOKEN_SECRET 
  --uids hm3d_val_v0.2 
  --data-path $DATA_DIR &&
After that, the error message is file: tarfile. ReadError: file could not be opened successfully

**Comment by imfks** [comment]
Check ur password, it's api token secret not the account password, or maybe u haven't send request to matterport?
I filled in [this](https://docs.google.com/forms/d/e/1FAIpQLScvTaDxQvHCT16ExB1IDOAh9js7Q7YpksMuTeyPPmIFnzuXmA/viewform), after getting their reply I downloaded the datasets again, then I successfully tar those files.

**Comment by orange0131** [comment]
> Check ur password, it's api token secret not the account password, or maybe u haven't send request to matterport? I filled in [this](https://docs.google.com/forms/d/e/1FAIpQLScvTaDxQvHCT16ExB1IDOAh9js7Q7YpksMuTeyPPmIFnzuXmA/viewform), after getting their reply I downloaded the datasets again, then I successfully tar those files.

Okay, I submitted my application yesterday, how long does it take to get it through

**Comment by imfks** [comment]
I recieved their email after four days, but I don't know if it's four days for everyone.

**Comment by orange0131** [comment]
> I recieved their email after four days, but I don't know if it's four days for everyone.
Hello, I approved the application, and then ran the command and started the download, but there was an error after downloading:
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by orange0131** [comment]
> I recieved their email after four days, but I don't know if it's four days for everyone.
Hello, I approved the application, and then ran the command and started the download, but there was an error after downloading:
100 27.1G  100 27.1G    0     0   9.8M      0  0:47:10  0:47:10 --:--:-- 10.3M
Traceback (most recent call last):
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/orange/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1797, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by Roberyan** [comment]
@orange0131 
I got the same problem after applying for the permission:
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
    main(sys.argv[1:])
  File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
    download_and_place(
  File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/home/user/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1826, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```
Did you solve this problem?

**Comment by qwer137559** [comment]
> @orange0131 I got the same problem after applying for the permission:
> 
> ```
> Traceback (most recent call last):
>   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
>     main(sys.argv[1:])
>   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
>     download_and_place(
>   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
>     with tarfile.open(data_path + package_name, "r:*") as tar_ref:
>   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1826, in open
>     raise ReadError("file could not be opened successfully")
> tarfile.ReadError: file could not be opened successfully
> ```
> 
> Did you solve this problem?

Currently，did you solve this problem?

**Comment by Roberyan** [comment]
> > @orange0131 I got the same problem after applying for the permission:
> > ```
> > Traceback (most recent call last):
> >   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 772, in <module>
> >     main(sys.argv[1:])
> >   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 766, in main
> >     download_and_place(
> >   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_sim/utils/datasets_download.py", line 602, in download_and_place
> >     with tarfile.open(data_path + package_name, "r:*") as tar_ref:
> >   File "/home/user/anaconda3/envs/vlfm/lib/python3.9/tarfile.py", line 1826, in open
> >     raise ReadError("file could not be opened successfully")
> > tarfile.ReadError: file could not be opened successfully
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did you solve this problem?
> 
> Currently，did you solve this problem?

I got it, my problem is that the permission is not granted yet, after about a week, my account works.

**Comment by zhaoyu199201** [comment]
command error not solved, I download one by one manually.
