### ISSUE TITLE
“ConnectionResetError: [Errno 104] Connection reset by peer” 

### ISSUE THREAD

**Issue by Benson722** [bdaiinstitute/vlfm#44]
Hi,
    When I try to run "`python -m vlfm.run`", some error occur:

cmd:
```python
Platform::WindowlessEglApplication::tryCreateContext(): cannot get default EGL display: EGL_BAD_PARAMETER
WindowlessContext: Unable to create windowless context
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/zhangyiqing/vlfm/vlfm/run.py", line 55, in main
    execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/run.py", line 62, in execute_exp
    trainer.eval()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/common/base_trainer.py", line 132, in eval
    self._eval_checkpoint(
  File "/home/zhangyiqing/vlfm/vlfm/utils/vlfm_trainer.py", line 99, in _eval_checkpoint
    self._init_envs(config, is_eval=True)
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/rl/ppo/ppo_trainer.py", line 142, in _init_envs
    self.envs = construct_envs(
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/common/construct_vector_env.py", line 94, in construct_envs
    envs = vector_env_cls(
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/core/vector_env.py", line 204, in __init__
    self.observation_spaces = [
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/core/vector_env.py", line 205, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/core/vector_env.py", line 108, in __call__
    res = self.read_fn()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Exception ignored in: <function VectorEnv.__del__ at 0x7f4f488f60d0>
Traceback (most recent call last):
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/core/vector_env.py", line 589, in __del__
    self.close()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/core/vector_env.py", line 457, in close
    read_fn()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/core/vector_env.py", line 108, in __call__
    res = self.read_fn()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/site-packages/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/zhangyiqing/miniconda3/envs/vlfm/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 

``` 

I am a liitle confused about the error. Should I rebuild the environment?

ps: `./scripts/launch_vlm_servers.sh` is running successfully.

My code environment:
```python
(vlfm) zhangyiqing@zyq:~/vlfm$ conda list
# packages in environment at /home/zhangyiqing/miniconda3/envs/vlfm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
blis                      0.7.11                   pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
brotli-python             1.0.9            py39h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.7.2             h06a4308_0  
cachetools                5.4.0                    pypi_0    pypi
catalogue                 2.0.10                   pypi_0    pypi
certifi                   2024.7.4         py39h06a4308_0  
cfgv                      3.4.0                    pypi_0    pypi
charset-normalizer        3.3.2              pyhd3eb1b0_0  
click                     8.1.7                    pypi_0    pypi
cloudpathlib              0.18.1                   pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
confection                0.1.5                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contexttimer              0.3.3                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.5                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
cymem                     2.0.8                    pypi_0    pypi
cython                    3.0.10                   pypi_0    pypi
dash                      2.17.1                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
depth-camera-filtering    0.1                      pypi_0    pypi
distlib                   0.3.8                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fairscale                 0.4.4                    pypi_0    pypi
faster-fifo               1.4.7                    pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1           py39h06a4308_0  
flask                     3.0.3                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frontier-exploration      0.1                      pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
ftfy                      6.2.0                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py39heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.32.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
groundingdino             0.1.0                    pypi_0    pypi
grpcio                    1.65.2                   pypi_0    pypi
gym                       0.23.0                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
habitat-baselines         0.2.420230405            pypi_0    pypi
habitat-lab               0.2.420230405            pypi_0    pypi
habitat-sim               0.2.4                    pypi_0    pypi
huggingface-hub           0.24.5                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
identify                  2.6.0                    pypi_0    pypi
idna                      3.7              py39h06a4308_0  
ifcfg                     0.24                     pypi_0    pypi
imageio                   2.34.2                   pypi_0    pypi
imageio-ffmpeg            0.5.1                    pypi_0    pypi
importlib-metadata        8.2.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306  
iopath                    0.1.10                   pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.3                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4            py39h06a4308_0  
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_2  
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.11                   pypi_0    pypi
kaggle                    1.6.17                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
langcodes                 3.4.0                    pypi_0    pypi
language-data             1.2.0                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.10.1.7                      0    nvidia
libcurand                 10.3.6.82                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h5eee18b_3  
libidn2                   2.3.4                h5eee18b_0  
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libwebp-base              1.3.2                h5eee18b_0  
llvm-openmp               14.0.6               h9e868ea_0  
llvmlite                  0.43.0                   pypi_0    pypi
lmdb                      1.5.1                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1  
magnum                    0.0.0                    pypi_0    pypi
marisa-trie               1.2.0                    pypi_0    pypi
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3            py39h5eee18b_0  
matplotlib                3.9.1                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344  
mkl-service               2.4.0            py39h5eee18b_1  
mkl_fft                   1.3.8            py39h5eee18b_0  
mkl_random                1.2.4            py39hdb19cb5_0  
mobile-sam                1.0                      pypi_0    pypi
moviepy                   1.0.3                    pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.3.0            py39h06a4308_0  
msgpack                   1.0.8                    pypi_0    pypi
murmurhash                1.0.10                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1  
networkx                  3.2.1            py39h06a4308_0  
nodeenv                   1.9.1                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.4           py39h5f9d8c6_0  
numpy-base                1.26.4           py39hb5e798b_0  
numpy-quaternion          2023.0.4                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
objectio                  0.2.29                   pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.5.5.64                 pypi_0    pypi
opendatasets              0.1.22                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h9ca470c_2  
openssl                   3.0.14               h5eee18b_0  
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pillow                    10.4.0           py39h5eee18b_0  
pip                       24.0             py39h06a4308_0  
platformdirs              4.2.2                    pypi_0    pypi
plotly                    5.23.0                   pypi_0    pypi
portalocker               2.10.1                   pypi_0    pypi
pre-commit                3.8.0                    pypi_0    pypi
preshed                   3.0.9                    pypi_0    pypi
proglog                   0.1.10                   pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pyasn1                    0.6.0                    pypi_0    pypi
pyasn1-modules            0.4.0                    pypi_0    pypi
pycocoevalcap             1.2                      pypi_0    pypi
pycocotools               2.0.8                    pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydeck                    0.9.1                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.19               h955ad1f_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-magic              0.4.27                   pypi_0    pypi
python-slugify            8.0.4                    pypi_0    pypi
pytorch                   2.3.1           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1            py39h5eee18b_0  
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
regex                     2024.7.24                pypi_0    pypi
requests                  2.32.3           py39h06a4308_0  
requests-oauthlib         2.0.0                    pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.19.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
salesforce-lavis          1.0.2                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                69.5.1           py39h06a4308_0  
shellingham               1.5.4                    pypi_0    pypi
simplejson                3.19.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smart-open                7.0.4                    pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
spacy                     3.7.5                    pypi_0    pypi
spacy-legacy              3.0.12                   pypi_0    pypi
spacy-loggers             1.0.5                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
srsly                     2.4.8                    pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
streamlit                 1.37.0                   pypi_0    pypi
supervision               0.22.0                   pypi_0    pypi
sympy                     1.12             py39h06a4308_0  
tbb                       2021.8.0             hdb19cb5_0  
tenacity                  8.5.0                    pypi_0    pypi
tensorboard               2.8.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
thinc                     8.2.5                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.7.24                pypi_0    pypi
timm                      0.4.12                   pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torchaudio                2.3.1                py39_cu118    pytorch
torchtriton               2.3.1                      py39    pytorch
torchvision               0.18.1               py39_cu118    pytorch
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
transformers              4.26.0                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing_extensions         4.11.0           py39h06a4308_0  
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2            py39h06a4308_0  
virtualenv                20.26.3                  pypi_0    pypi
vlfm                      0.1                      pypi_0    pypi
wasabi                    1.1.3                    pypi_0    pypi
watchdog                  4.0.1                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
weasel                    0.4.1                    pypi_0    pypi
webdataset                0.1.40                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0  
widgetsnbextension        4.0.11                   pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.40.2                   pypi_0    pypi
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
zstd                      1.5.5                hc292b87_2  

```

**Comment by naokiyokoyama** [comment]
The relevant error is 
Platform::WindowlessEglApplication::tryCreateContext(): cannot get default EGL display: EGL_BAD_PARAMETER
WindowlessContext: Unable to create windowless context

this is an issue with your habitat installation. It's best to open an issue on the habitat repos to solve your issue

**Comment by Benson722** [comment]
The problem has been solved by upgrading the NVIDIA driver from 550 to 560. My GPU device is 4090. Maybe the driver and openGL version don't match well.

**Comment by naiyouFF** [comment]
Hi, I would like to ask if this code will have a visualization to display, and will there be a popup for the habitat interface?
