### ISSUE TITLE
Question for eval on gibson dataset

### ISSUE THREAD

**Issue by NormanMises** [bdaiinstitute/vlfm#54]
Hello, I'm trying to run vlfm's validation on Gibson [vlfm/semexp_env/eval.py](https://github.com/bdaiinstitute/vlfm/blob/main/vlfm/semexp_env/eval.py) and I'm starting with [here]( https://github.com/bdaiinstitute/vlfm/issues/40#issuecomment-2231646818) Obtained [semexp_policy. py](https://github.com/bdaiinstitute/vlfm/blob/456ccef4a0a9ba2fdc863c0371e1e015298b3e30/vlfm/semexp_env/semexp_policy.py), but I'm not sure how to configure the environment in which it runs, because [Original Codebase](https://github.com/devendrachaplot/Object-Goal-Navigation/blob/5d76902fe9be821926a1de32557ca9a8dc21d0f5/README.md) The exact version of python required is not specified, and After installed the version of habitat-sim/lab of this repository, installing the 0.1.5 version always gives all kinds of errors...
Pls can someone give more detailed steps, thank you in advance!

你好，我在尝试运行vlfm在Gibson上的验证 [vlfmmexp_env/eval.py](https://github.com/bdaiinstitute/vlfm/blob/main/vlfm/semexp_env/eval.py)，我从 [这里](https://github.com/bdaiinstitute/vlfm/issues/40#issuecomment-2231646818) 获得了 [semexp_policy.py](https://github.com/bdaiinstitute/vlfm/blob/456ccef4a0a9ba2fdc863c0371e1e015298b3e30/vlfm/semexp_env/semexp_policy.py) ，但是我不确定该如何配置运行的环境，因为 [原代码库](https://github.com/devendrachaplot/Object-Goal-Navigation/blob/5d76902fe9be821926a1de32557ca9a8dc21d0f5/README.md) 并没有指明确切需要的python版本，以及在安装了本仓库的habitat-sim/lab 版本之后再安装0.1.5的版本总是会出各种各样的错误。。。
请问有人可以给出更详细的步骤吗，提前感谢！

**Comment by Sellaris** [comment]
So can i get some advise?Thank u！

**Comment by NormanMises** [comment]
> So can i get some advise?Thank u！

作者的 Gibson 验证好像也用的是点导航，但是没发模型权重，我是把最后导航的部分改成了 fmm 基于 PONI 的代码

跑的效果只有原来的一半

**Comment by Sellaris** [comment]
> > 那么我能得到一些建议吗？谢谢！
> 
> 作者的 Gibson 验证好像也用的是点导航，但是没发模型权重，我是把最后导航的部分改成了 fmm 基于 PONI 的代码
> 
> 跑的效果只有原来的一半

感谢！我在GAMAP（N-IPS2024）上看到了VLFM+FMM的，结果 是SR=50.9，SPL=23.6

**Comment by luyuanOo** [comment]
你好！我最近准备在 Gibson 数据集上评估 VLFM ，但是我遇到了一些问题，请问能麻烦你给我一些建议吗？

我已经从Gibson 官网下载了gibson_habitat_trainval.zip（10G），gibson_habitat.zip（1.5G），我应该使用哪一个呢？

我尝试去论文提到的SemExp的项目https://github.com/devendrachaplot/Object-Goal-Navigation去下载episode dataset，通过https://drive.google.com/uc?export=download&id=1tslnZAkH8m3V5nP8pbtBmaR2XEfr8Rau下载之后得到objectnav_gibson_v1.1.zip（211 KB ），objectnav_gibson_v1.1.zip里面的train.json.gz和val.json.gz里面都只有episodes:[]这一句。
是我下载的这个episode dataset是错误的吗？可是我也找不到别的地方可以下载了。

hm3d的episode dataset里面设置了category_to_task_category_id，
![Image](https://github.com/user-attachments/assets/3b353647-f67a-40ee-bd7a-944ffbcfe15d)
可是我并没有找到VLFM这个代码和论文里有哪里提到关于gibson的category_to_task_category_id？

配置好datass的路径之后我尝试运行python -m vlfm.run habitat.dataset.data_path=data/datasets/objectnav/gibson/v1/train/train.json.gz
可是出现以下报错：
```
2025-05-19 14:12:34,944 Initializing dataset ObjectNav-v1
Error executing job with overrides: ['habitat.dataset.data_path=data/datasets/objectnav/gibson/v1/train/train.json.gz']
Traceback (most recent call last):
  File "/home/jialuyuan/vlfm/vlfm/run.py", line 56, in main
    execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/run.py", line 62, in execute_exp
    trainer.eval()
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/common/base_trainer.py", line 132, in eval
    self._eval_checkpoint(
  File "/home/jialuyuan/vlfm/vlfm/utils/vlfm_trainer.py", line 100, in _eval_checkpoint
    self._init_envs(config, is_eval=True)
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/rl/ppo/ppo_trainer.py", line 141, in _init_envs
    self.envs = construct_envs(
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/common/construct_vector_env.py", line 40, in construct_envs
    scenes = dataset.get_scenes_to_load(config.habitat.dataset)
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py", line 58, in get_scenes_to_load
    dataset = cls(cfg)
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/object_nav/object_nav_dataset.py", line 76, in __init__
    super().__init__(config)
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py", line 101, in __init__
    self.from_json(f.read(), scenes_dir=config.scenes_dir)
  File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/object_nav/object_nav_dataset.py", line 112, in from_json
    assert len(self.category_to_task_category_id) == len(
AttributeError: 'ObjectNavDatasetV1' object has no attribute 'category_to_task_category_id'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by NormanMises** [comment]
> 你好！我最近准备在 Gibson 数据集上评估 VLFM ，但是我遇到了一些问题，请问能麻烦你给我一些建议吗？
> 
> 我已经从Gibson 官网下载了gibson_habitat_trainval.zip（10G），gibson_habitat.zip（1.5G），我应该使用哪一个呢？
> 
> 我尝试去论文提到的SemExp的项目[https://github.com/devendrachaplot/Object-Goal-Navigation去下载episode](https://github.com/devendrachaplot/Object-Goal-Navigation%E5%8E%BB%E4%B8%8B%E8%BD%BDepisode) dataset，通过[https://drive.google.com/uc?export=download&id=1tslnZAkH8m3V5nP8pbtBmaR2XEfr8Rau下载之后得到objectnav_gibson_v1.1.zip（211](https://drive.google.com/uc?export=download&id=1tslnZAkH8m3V5nP8pbtBmaR2XEfr8Rau%E4%B8%8B%E8%BD%BD%E4%B9%8B%E5%90%8E%E5%BE%97%E5%88%B0objectnav_gibson_v1.1.zip%EF%BC%88211) KB ），objectnav_gibson_v1.1.zip里面的train.json.gz和val.json.gz里面都只有episodes:[]这一句。 是我下载的这个episode dataset是错误的吗？可是我也找不到别的地方可以下载了。
> 
> hm3d的episode dataset里面设置了category_to_task_category_id， ![Image](https://github.com/user-attachments/assets/3b353647-f67a-40ee-bd7a-944ffbcfe15d) 可是我并没有找到VLFM这个代码和论文里有哪里提到关于gibson的category_to_task_category_id？
> 
> 配置好datass的路径之后我尝试运行python -m vlfm.run habitat.dataset.data_path=data/datasets/objectnav/gibson/v1/train/train.json.gz 可是出现以下报错：
> 
> ```
> 2025-05-19 14:12:34,944 Initializing dataset ObjectNav-v1
> Error executing job with overrides: ['habitat.dataset.data_path=data/datasets/objectnav/gibson/v1/train/train.json.gz']
> Traceback (most recent call last):
>   File "/home/jialuyuan/vlfm/vlfm/run.py", line 56, in main
>     execute_exp(cfg, "eval" if cfg.habitat_baselines.evaluate else "train")
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/run.py", line 62, in execute_exp
>     trainer.eval()
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/common/base_trainer.py", line 132, in eval
>     self._eval_checkpoint(
>   File "/home/jialuyuan/vlfm/vlfm/utils/vlfm_trainer.py", line 100, in _eval_checkpoint
>     self._init_envs(config, is_eval=True)
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/rl/ppo/ppo_trainer.py", line 141, in _init_envs
>     self.envs = construct_envs(
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat_baselines/common/construct_vector_env.py", line 40, in construct_envs
>     scenes = dataset.get_scenes_to_load(config.habitat.dataset)
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py", line 58, in get_scenes_to_load
>     dataset = cls(cfg)
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/object_nav/object_nav_dataset.py", line 76, in __init__
>     super().__init__(config)
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/pointnav/pointnav_dataset.py", line 101, in __init__
>     self.from_json(f.read(), scenes_dir=config.scenes_dir)
>   File "/home/jialuyuan/anaconda3/envs/vlfm/lib/python3.9/site-packages/habitat/datasets/object_nav/object_nav_dataset.py", line 112, in from_json
>     assert len(self.category_to_task_category_id) == len(
> AttributeError: 'ObjectNavDatasetV1' object has no attribute 'category_to_task_category_id'
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
> ```

我也记不太清了，你先把poni复现成功，然后把vlfm semexp的代码移到poni里运行

**Comment by luyuanOo** [comment]
谢谢你！我再尝试一下。

**Comment by womeizhaol** [comment]
> Hello, I'm trying to run vlfm's validation on Gibson [vlfm/semexp_env/eval.py](https://github.com/bdaiinstitute/vlfm/blob/main/vlfm/semexp_env/eval.py) and I'm starting with [here](https://github.com/bdaiinstitute/vlfm/issues/40#issuecomment-2231646818) Obtained [semexp_policy. py](https://github.com/bdaiinstitute/vlfm/blob/456ccef4a0a9ba2fdc863c0371e1e015298b3e30/vlfm/semexp_env/semexp_policy.py), but I'm not sure how to configure the environment in which it runs, because [Original Codebase](https://github.com/devendrachaplot/Object-Goal-Navigation/blob/5d76902fe9be821926a1de32557ca9a8dc21d0f5/README.md) The exact version of python required is not specified, and After installed the version of habitat-sim/lab of this repository, installing the 0.1.5 version always gives all kinds of errors... Pls can someone give more detailed steps, thank you in advance!
> 
> 你好，我在尝试运行vlfm在Gibson上的验证 [vlfmmexp_env/eval.py](https://github.com/bdaiinstitute/vlfm/blob/main/vlfm/semexp_env/eval.py)，我从 [这里](https://github.com/bdaiinstitute/vlfm/issues/40#issuecomment-2231646818) 获得了 [semexp_policy.py](https://github.com/bdaiinstitute/vlfm/blob/456ccef4a0a9ba2fdc863c0371e1e015298b3e30/vlfm/semexp_env/semexp_policy.py) ，但是我不确定该如何配置运行的环境，因为 [原代码库](https://github.com/devendrachaplot/Object-Goal-Navigation/blob/5d76902fe9be821926a1de32557ca9a8dc21d0f5/README.md) 并没有指明确切需要的python版本，以及在安装了本仓库的habitat-sim/lab 版本之后再安装0.1.5的版本总是会出各种各样的错误。。。 请问有人可以给出更详细的步骤吗，提前感谢！

May I ask if you have successfully evaluated on the mp3d and Gibson datasets? Can I consult you about this? Also, how can I download the mp3d and Gibson datasets?
